package com.example.appdatcomtam.Navigation

enum class Screen(val route: String) {
    LoginScreen("LoginScreen"),
    SignUp("SignUp"),
    Home("Home"),
    Category("Favorite"),
    QuanLyMonAnScreen("QuanLyMonAnScreen"),
    Profile("Profile"),
    MyBottombar("MyBottombar"),
    History("History"),
    Cart("Cart"),
    Thongke("Thongke"),
    Manager("Manager"),
    ThemMonAn("ThemMonAn"),
    SuaMonAn("SuaMonAn"),
    DanhSachMonAn("DanhSachMonAn"),
    QuanLyLoaiMonAnScreen("QuanLyLoaiMonAnScreen"),
    AddLoaiMonAnScreen("AddLoaiMonAnScreen"),
    LoaiMonAnListScreen("LoaiMonAnListScreen"),
    EditLoaiMonAnScreen("EditLoaiMonAnScreen"),
    DeleteLoaiMonan("DeleteLoaiMonan"),
    DeatailDonHang("DeatailDonHang"),
    QuanlysLoaiMAvaMonAn("QuanlysLoaiMAvaMonAn"),
}
